# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(choices=[(1, '1° semestre'), (2, '2° semestre'), (3, '3° semestre'), (4, '4° semestre'), (5, '5° semestre'), (6, '6° semestre'), (7, '7° semestre'), (8, '8° semestre'), (9, '9° semestre'), (10, '10° semestre'), (11, '11° semestre'), (12, '12° semestre')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
