# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20170528_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Presidente'), (2, 'Secretario'), (3, 'Vocal'), (4, 'Suplente')], default=1),
        ),
    ]
