# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_profesor_creditos_admin'),
        ('sistema', '0005_auto_20170529_0926'),
    ]

    operations = [
    ]
