# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_merge_20170530_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='rol',
        ),
    ]
