# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Profesor')),
            ],
        ),
    ]
