# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_remove_profesor_rol'),
        ('titulacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulacion',
            name='profesor',
        ),
        migrations.AddField(
            model_name='titulacion',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2017, 5, 30, 18, 57, 15, 241749, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2017, 5, 30, 18, 57, 15, 241724, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='presidente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presidente+', to='sistema.Profesor'),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='secretario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secretario+', to='sistema.Profesor'),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='suplente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suplente+', to='sistema.Profesor'),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='vocal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vocal+', to='sistema.Profesor'),
        ),
    ]
