# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0002_auto_20170530_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='revision_1',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 23, 18, 54, 685032, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='revision_2',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 23, 18, 54, 685045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 23, 18, 54, 685017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 23, 18, 54, 684988, tzinfo=utc)),
        ),
    ]
