# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('total_creditos', models.IntegerField()),
                ('estatus', models.IntegerField(choices=[(1, 'Por aprobar'), (2, 'Aprobada'), (3, 'Terminada')], default=1)),
                ('alumnos', models.ManyToManyField(to='sistema.Alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Profesor')),
            ],
        ),
    ]
