# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='sistema.Alumno'),
        ),
    ]
