# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20170528_0749'),
        ('creditos', '0002_auto_20170528_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='candidatos',
            field=models.ManyToManyField(blank=True, related_name='actividades_solicitada', to='sistema.Alumno'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='sistema.Alumno'),
        ),
    ]
