# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_auto_20170528_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='candidatos',
            field=models.ManyToManyField(blank=True, related_name='actividades_solicitadas', to='sistema.Alumno'),
        ),
    ]
